version: '3'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
    - 8083:8080
  # Redis Service
  redis:
    image: redis:alpine

# Volumes
volumes:
  dbdata:
    driver: local
